### ISSUE TITLE
Support indexing and iteration by grapheme clusters

### ISSUE THREAD

**Issue by pyjarrett** [AdaCore/VSS#109]
## Problem

While graphemes demarcate groups of UTF-8 code points into units, grapheme clusters indicate sets of graphemes which together form one "displayable unit."  This "displayable unit" is critical for when dealing with textual interfaces, as a cursor needs to move and delete by grapheme clusters, not by graphemes or individual bytes, to ensure the cursor remains at proper boundaries and the data remains valid displayable UTF-8.

## Example

Suppose a string with graphemes "xyapqr" and a hypothetical grouping of grapheme clusters:
```
# x1 indicates byte 1 of grapheme x, x2 is 2nd byte of x, etc.
grapheme cluster 1: x1 x2 x3 y1 y2 (5 bytes)
grapheme cluster 2: a1 a2 (2 bytes)
grapheme cluster 3: p1 p2 q1 q2 q3 r1 r2 r3 (8 bytes)

grapheme cluster boundaries
|              |      |
v              v      v
x1 x2 x3 y1 y2 a1 a2  p1 p2 q1 q2 q3 r1 r2 r3
```

## Requested Behavior

- Iterating over such a string `for BytePosition of Grapheme_Cluster_Iterator(S)` should return byte positions of x1, a1, and p1 in turn.
- Indexing by grapheme clusters 1, 2 and 3 `S.Grapheme_Cluster(Index)` should return byte positions of x1, a1 and p1 respectively.

**Comment by godunko** [comment]
Thank you for opening an interesting issue!

Unfortunately, it is not implemented now and will take some time to implement it.

**Comment by godunko** [comment]
Initial implementation of Grapheme_Cluster_Iterator has been added. It works like other text elements iterators, First_Grapheme_Cluster subprogram can be used to create iterator pointing to first grapheme cluster in the string; Forward/Backward subprograms of the iterator move iterator to the next/previous grapheme cluster, First_Character_Index/Last_Character_Index subprograms return index of the first/last character of the grapheme cluster, while First_UTF8_Offset/Last_UTF8_Offset return their equivalents in the UTF-8 encoded byte sequence.
