### ISSUE TITLE
API documentation link is broken

### ISSUE THREAD

**Issue by JeremyGrosser** [AdaCore/VSS#191]
The "API Reference" link in the README points to a 404 page.

**Comment by JeremyGrosser** [comment]
Looks like the PR #190 already fixes this.

**Comment by godunko** [comment]
Thank you for report, PR #190 has been merged and it is fixed now.

**Comment by iandoug** [comment]
Broken again?

**Comment by godunko** [comment]
It works for me. Which URL doesn't work on you side?

**Comment by iandoug** [comment]
https://github.com/AdaCore/VSS/blob/master/docs/html/index.html

from
https://github.com/AdaCore/VSS -> docs -> API Reference

**Comment by godunko** [comment]
This link is definitely broken, thank you very much for report and help with investigation. We'll fix it.

**Comment by iandoug** [comment]
"Right now you can use link on the main page of the project."

Does not seem to work?

**Comment by godunko** [comment]
It is fixed now.
