### ISSUE TITLE
Command_Line

### ISSUE THREAD

**Issue by HROMANO** [AdaCore/VSS#208]
Hi,

I'd like to have some syntax like this for a command line program:

```
my_prog [global_options] <command> [command_options] <command_arguments>
```

For example:
- `my_prog search --help` would only give help for the `search` command, 
- `my_prog --dark-theme info -l dupont` would apply `--dark-theme` as a global option for `my_prog` and `-l` would only relate to the `info` command.

But I don't see how to achieve this with VSS.Command_Line.

Binary_Option, Name_Value_Option and Value_Option are all put before positional options whatever the order I use Add_Option.

Is such syntax possible with `VSS.Command_Line`?

Thanks

**Comment by godunko** [comment]
You need to use VSS.Command_Line.Parsers to achieve something like this. An idea behind is to add only global options and command positional parameter at first stage, parse arguments, add options/parameters of the specified command, and reparse arguments once more.

However, any options still can be specified at any place: before and after command parameter, it is design of the parser.

We will add an example soon.

**Comment by HROMANO** [comment]
Thank you for the example. I'll try that. It should be sufficient for my use case (and way simpler than using CLIC).
